name: JDCNC
board: unknown

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

# kinematics:
#   Cartesian:

stepping:
  engine: I2S_STREAM
  idle_ms: 250
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: I2SO.8
  x:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 300.000
    soft_limits: false
    motor0:
      limit_neg_pin: gpio.39:low
      limit_pos_pin: gpio.36:low
      hard_limits: true
      standard_stepper:
        direction_pin: I2SO.0
        step_pin: I2SO.1
        disable_pin: NO_PIN
    motor1:
      limit_neg_pin: gpio.35:low
      limit_pos_pin: gpio.34:low
      hard_limits: true
      standard_stepper:
        direction_pin: I2SO.2
        step_pin: I2SO.3
    homing:
      cycle: 2
  y:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 300.000
    soft_limits: false
    motor0:
      limit_neg_pin: gpio.33:low
      limit_pos_pin: gpio.32:low
      hard_limits: true
      standard_stepper:
        direction_pin: I2SO.4
        step_pin: I2SO.5
    homing:
      cycle: 2
  z:
    steps_per_mm: 200.000
    max_rate_mm_per_min: 1000.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 300.000
    soft_limits: false
    motor0:
      limit_neg_pin: gpio.26:low
      limit_pos_pin: gpio.25:low
      hard_limits: true
      standard_stepper:
        direction_pin: I2SO.6
        step_pin: I2SO.7
    homing:
      cycle: 1

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5

# control:
#   reset_pin: gpio.34:low:pu
#   feed_hold_pin: gpio.36:low:pu
#   cycle_start_pin: gpio.39:low:pu

coolant:
  delay_ms: 1000.000

probe:
  pin: gpio.27:low
  check_mode_start: true

PWM:
  pwm_hz: 5000
  direction_pin: NO_PIN
  output_pin: gpio.2
  enable_pin: I2SO.14
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0.000% 10000=100.000%

macros:
  startup_line0: 
  startup_line1: 
  macro0: 
  macro1: 
  macro2: 
  macro3: 

start:
  must_home: true
  check_limits: true
  deactivate_parking: false

user_outputs:
arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: false 